baseURL = "http://yanlinlin82.github.io/ARTS-Weekly/"
title = "颜林林的“左耳听风ARTS”打卡记录"
theme = "simple-style"
paginate = 20
googleAnalytics = "UA-74397492-2"

[params]
githubURL = "https://github.com/yanlinlin82/ARTS-Weekly/"

[permalinks]
post = "/:slug/"
page = "/:slug/"

[[menu.main]]
weight = 10
name = "目录"
url = "/"

[[menu.main]]
weight = 20
name = "索引"
url = "/quick/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"

[[menu.main]]
weight = 99
name = "个人网站"
url = "http://yanlinlin.cn/"

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"
