baseURL = "http://yanlinlin82.github.io/ARTS-Weekly/"
title = "颜林林的“左耳听风ARTS”打卡记录"
theme = "simple-style"
paginate = 20
googleAnalytics = "UA-74397492-2"

[params]
githubURL = "https://github.com/yanlinlin82/ARTS-Weekly/"

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"

[permalinks]
post = "/:slug/"
page = "/:slug/"

[[menu.main]]
weight = 10
name = "目录"
url = "/"

[[menu.main]]
weight = 20
name = "算法(A)"
url = "/algorithm/"

[[menu.main]]
weight = 30
name = "调研(R)"
url = "/review/"

[[menu.main]]
weight = 40
name = "技巧(T)"
url = "/tip/"

[[menu.main]]
weight = 50
name = "分享(S)"
url = "/share/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"

[[menu.main]]
weight = 99
name = ">>个人网站"
url = "https://yanlinlin.cn/"
